import assert from "node:assert/strict";
import test from "node:test";

import { buildFocusDetailLabels } from "./focus-detail-labels";

test("buildFocusDetailLabels 会把 source 字段映射到详情组件结构", () => {
  const labels = buildFocusDetailLabels({
    detailTitle: "title",
    detailBackToCurrent: "back",
    detailFindRelations: "find",
    detailPrev: "prev",
    detailNext: "next",
    detailMoreActions: "more",
    detailManualAddRelated: "manual-add",
    detailRegenerateAudio: "regen-audio",
    detailRetryEnrichment: "retry-enrich",
    detailDeleteExpression: "delete-expression",
    detailOpenAsMain: "open-main",
    moveIntoCluster: "move-into",
    detachClusterMember: "detach",
    addThisExpression: "add",
    addingThisExpression: "adding",
    addedThisExpression: "added",
    completeAssist: "done",
    confirmCancel: "cancel",
    confirmContinue: "continue",
    detailOpenAsMainConfirmTitle: "confirm-main-title",
    detailOpenAsMainConfirmDesc: "confirm-main-desc",
    detachClusterMemberConfirmTitle: "confirm-detach-title",
    detachClusterMemberConfirmDesc: "confirm-detach-desc",
    detailDeleteExpressionConfirmTitle: "confirm-delete-title",
    detailDeleteExpressionConfirmDesc: "confirm-delete-desc",
    detailCandidateBadge: "candidate",
    noTranslation: "no-translation",
    detailLoading: "loading",
    detailTabInfo: "info",
    detailTabSavedSimilar: "similar",
    detailTabContrast: "contrast",
    commonUsage: "usage",
    typicalScenarioLabel: "scenario",
    semanticFocusLabel: "semantic",
    reviewStage: "review",
    usageHintFallback: "usage-fallback",
    typicalScenarioPending: "scenario-pending",
    semanticFocusPending: "semantic-pending",
    sourceSentence: "source",
    noSourceSentence: "no-source",
    detailSimilarHint: "similar-hint",
    focusEmptySimilar: "similar-empty",
    detailContrastHint: "contrast-hint",
    noContrastExpressions: "contrast-empty",
    speakSentence: "speak",
  });

  assert.deepEqual(labels, {
    title: "title",
    backToCurrent: "back",
    findRelations: "find",
    prev: "prev",
    next: "next",
    detailMoreActions: "more",
    detailManualAddRelated: "manual-add",
    detailRegenerateAudio: "regen-audio",
    detailRetryEnrichment: "retry-enrich",
    detailDeleteExpression: "delete-expression",
    detailOpenAsMain: "open-main",
    moveIntoCluster: "move-into",
    detachClusterMember: "detach",
    addThisExpression: "add",
    addingThisExpression: "adding",
    addedThisExpression: "added",
    completeAssist: "done",
    confirmCancel: "cancel",
    confirmContinue: "continue",
    detailOpenAsMainConfirmTitle: "confirm-main-title",
    detailOpenAsMainConfirmDesc: "confirm-main-desc",
    detachClusterMemberConfirmTitle: "confirm-detach-title",
    detachClusterMemberConfirmDesc: "confirm-detach-desc",
    detailDeleteExpressionConfirmTitle: "confirm-delete-title",
    detailDeleteExpressionConfirmDesc: "confirm-delete-desc",
    detailCandidateBadge: "candidate",
    noTranslation: "no-translation",
    detailLoading: "loading",
    detailTabInfo: "info",
    detailTabSavedSimilar: "similar",
    detailTabContrast: "contrast",
    commonUsage: "usage",
    typicalScenarioLabel: "scenario",
    semanticFocusLabel: "semantic",
    reviewStage: "review",
    usageHintFallback: "usage-fallback",
    typicalScenarioPending: "scenario-pending",
    semanticFocusPending: "semantic-pending",
    sourceSentence: "source",
    noSourceSentence: "no-source",
    detailSimilarHint: "similar-hint",
    focusEmptySimilar: "similar-empty",
    detailContrastHint: "contrast-hint",
    noContrastExpressions: "contrast-empty",
    speakSentence: "speak",
  });
});
