import assert from "node:assert/strict";
import test from "node:test";
import { buildFocusDetailLabels } from "./focus-detail-labels";

test("buildFocusDetailLabels 会稳定映射所有详情文案字段", () => {
  const labels = buildFocusDetailLabels({
    detailTitle: "详情标题",
    detailBackToCurrent: "回到当前",
    detailFindRelations: "查找关系",
    detailPrev: "上一条",
    detailNext: "下一条",
    detailMoreActions: "更多操作",
    detailOpenAsMain: "设为本簇主表达",
    moveIntoCluster: "移入当前表达簇",
    detachClusterMember: "设置为独立主表达",
    addThisExpression: "添加这个表达",
    confirmCancel: "取消",
    confirmContinue: "继续",
    detailOpenAsMainConfirmTitle: "确认设为主表达",
    detailOpenAsMainConfirmDesc: "会切换当前簇的主表达。",
    detachClusterMemberConfirmTitle: "确认独立",
    detachClusterMemberConfirmDesc: "会拆出当前表达。",
    detailCandidateBadge: "候选",
    noTranslation: "暂无翻译",
    detailLoading: "加载中",
    detailTabInfo: "详情",
    detailTabSavedSimilar: "同类",
    detailTabContrast: "对照",
    commonUsage: "常见用法",
    typicalScenarioLabel: "典型场景",
    semanticFocusLabel: "语义重点",
    reviewStage: "复习阶段",
    usageHintFallback: "暂无用法提示",
    typicalScenarioPending: "待补充场景",
    semanticFocusPending: "待补充语义重点",
    sourceSentence: "来源句子",
    noSourceSentence: "暂无来源句子",
    detailSimilarHint: "查看同类表达",
    focusEmptySimilar: "暂无同类表达",
    detailContrastHint: "查看对照表达",
    noContrastExpressions: "暂无对照表达",
    speakSentence: "朗读",
  });

  assert.deepEqual(labels, {
    title: "详情标题",
    backToCurrent: "回到当前",
    findRelations: "查找关系",
    prev: "上一条",
    next: "下一条",
    detailMoreActions: "更多操作",
    detailOpenAsMain: "设为本簇主表达",
    moveIntoCluster: "移入当前表达簇",
    detachClusterMember: "设置为独立主表达",
    addThisExpression: "添加这个表达",
    confirmCancel: "取消",
    confirmContinue: "继续",
    detailOpenAsMainConfirmTitle: "确认设为主表达",
    detailOpenAsMainConfirmDesc: "会切换当前簇的主表达。",
    detachClusterMemberConfirmTitle: "确认独立",
    detachClusterMemberConfirmDesc: "会拆出当前表达。",
    detailCandidateBadge: "候选",
    noTranslation: "暂无翻译",
    detailLoading: "加载中",
    detailTabInfo: "详情",
    detailTabSavedSimilar: "同类",
    detailTabContrast: "对照",
    commonUsage: "常见用法",
    typicalScenarioLabel: "典型场景",
    semanticFocusLabel: "语义重点",
    reviewStage: "复习阶段",
    usageHintFallback: "暂无用法提示",
    typicalScenarioPending: "待补充场景",
    semanticFocusPending: "待补充语义重点",
    sourceSentence: "来源句子",
    noSourceSentence: "暂无来源句子",
    detailSimilarHint: "查看同类表达",
    focusEmptySimilar: "暂无同类表达",
    detailContrastHint: "查看对照表达",
    noContrastExpressions: "暂无对照表达",
    speakSentence: "朗读",
  });
});
