export type FocusDetailSheetLabels = {
  title: string;
  backToCurrent: string;
  findRelations: string;
  prev: string;
  next: string;
  detailMoreActions: string;
  detailOpenAsMain: string;
  moveIntoCluster: string;
  detachClusterMember: string;
  addThisExpression: string;
  confirmCancel: string;
  confirmContinue: string;
  detailOpenAsMainConfirmTitle: string;
  detailOpenAsMainConfirmDesc: string;
  detachClusterMemberConfirmTitle: string;
  detachClusterMemberConfirmDesc: string;
  detailCandidateBadge: string;
  noTranslation: string;
  detailLoading: string;
  detailTabInfo: string;
  detailTabSavedSimilar: string;
  detailTabContrast: string;
  commonUsage: string;
  typicalScenarioLabel: string;
  semanticFocusLabel: string;
  reviewStage: string;
  usageHintFallback: string;
  typicalScenarioPending: string;
  semanticFocusPending: string;
  sourceSentence: string;
  noSourceSentence: string;
  detailSimilarHint: string;
  focusEmptySimilar: string;
  detailContrastHint: string;
  noContrastExpressions: string;
  speakSentence: string;
};

type FocusDetailLabelSource = {
  detailTitle: string;
  detailBackToCurrent: string;
  detailFindRelations: string;
  detailPrev: string;
  detailNext: string;
  detailMoreActions: string;
  detailOpenAsMain: string;
  moveIntoCluster: string;
  detachClusterMember: string;
  addThisExpression: string;
  confirmCancel: string;
  confirmContinue: string;
  detailOpenAsMainConfirmTitle: string;
  detailOpenAsMainConfirmDesc: string;
  detachClusterMemberConfirmTitle: string;
  detachClusterMemberConfirmDesc: string;
  detailCandidateBadge: string;
  noTranslation: string;
  detailLoading: string;
  detailTabInfo: string;
  detailTabSavedSimilar: string;
  detailTabContrast: string;
  commonUsage: string;
  typicalScenarioLabel: string;
  semanticFocusLabel: string;
  reviewStage: string;
  usageHintFallback: string;
  typicalScenarioPending: string;
  semanticFocusPending: string;
  sourceSentence: string;
  noSourceSentence: string;
  detailSimilarHint: string;
  focusEmptySimilar: string;
  detailContrastHint: string;
  noContrastExpressions: string;
  speakSentence: string;
};

export const buildFocusDetailLabels = (
  source: FocusDetailLabelSource,
): FocusDetailSheetLabels => ({
  title: source.detailTitle,
  backToCurrent: source.detailBackToCurrent,
  findRelations: source.detailFindRelations,
  prev: source.detailPrev,
  next: source.detailNext,
  detailMoreActions: source.detailMoreActions,
  detailOpenAsMain: source.detailOpenAsMain,
  moveIntoCluster: source.moveIntoCluster,
  detachClusterMember: source.detachClusterMember,
  addThisExpression: source.addThisExpression,
  confirmCancel: source.confirmCancel,
  confirmContinue: source.confirmContinue,
  detailOpenAsMainConfirmTitle: source.detailOpenAsMainConfirmTitle,
  detailOpenAsMainConfirmDesc: source.detailOpenAsMainConfirmDesc,
  detachClusterMemberConfirmTitle: source.detachClusterMemberConfirmTitle,
  detachClusterMemberConfirmDesc: source.detachClusterMemberConfirmDesc,
  detailCandidateBadge: source.detailCandidateBadge,
  noTranslation: source.noTranslation,
  detailLoading: source.detailLoading,
  detailTabInfo: source.detailTabInfo,
  detailTabSavedSimilar: source.detailTabSavedSimilar,
  detailTabContrast: source.detailTabContrast,
  commonUsage: source.commonUsage,
  typicalScenarioLabel: source.typicalScenarioLabel,
  semanticFocusLabel: source.semanticFocusLabel,
  reviewStage: source.reviewStage,
  usageHintFallback: source.usageHintFallback,
  typicalScenarioPending: source.typicalScenarioPending,
  semanticFocusPending: source.semanticFocusPending,
  sourceSentence: source.sourceSentence,
  noSourceSentence: source.noSourceSentence,
  detailSimilarHint: source.detailSimilarHint,
  focusEmptySimilar: source.focusEmptySimilar,
  detailContrastHint: source.detailContrastHint,
  noContrastExpressions: source.noContrastExpressions,
  speakSentence: source.speakSentence,
});
