export type ReviewPageLabels = {
  loadFailed: string;
  submitFailed: string;
  submitOk: string;
  eyebrow: string;
  title: string;
  desc: string;
  dueNow: string;
  doneToday: string;
  accuracy: string;
  statusJoiner: string;
  trainingGuidePrefix: string;
  trainingGuideSuffix: string;
  trainingHintSubtle: string;
  expressionLabel: string;
  exampleLabel: string;
  showReference: string;
  hideReference: string;
  activeRecallHint: string;
  againLabel: string;
  hardLabel: string;
  goodLabel: string;
  queueLoading: string;
  queueEmpty: string;
  noTranslation: string;
  sourceSentence: string;
  reviewStats: string;
  correct: string;
  incorrect: string;
  dash: string;
  sessionHint: string;
  manualSessionHint: string;
  manualTrainingHintSubtle: string;
  fromExpressionLibrary: string;
  fromExpressionMap: string;
  fromTodayTask: string;
  fromSelected: string;
  sourcePrefix: string;
  defaultHint: string;
};

export const reviewPageLabels: ReviewPageLabels = {
  loadFailed: "加载复习数据失败。",
  submitFailed: "提交复习失败。",
  submitOk: "已记录复习结果。",
  eyebrow: "复习",
  title: "巩固已保存表达",
  desc: "把已保存表达跑进真实复习闭环，持续形成可输出能力。",
  dueNow: "当前待复习",
  doneToday: "今日已复习",
  accuracy: "复习正确率",
  statusJoiner: "·",
  trainingGuidePrefix: "先在心里说一句，再判断你现在的",
  trainingGuideSuffix: "熟悉程度",
  trainingHintSubtle: "别急着看参考句，先自己试一下",
  expressionLabel: "表达",
  exampleLabel: "参考句",
  showReference: "想不起来？看参考句",
  hideReference: "收起参考句",
  activeRecallHint: "在心里说一遍，或用你自己的话试着改写一句",
  againLabel: "不会",
  hardLabel: "有点难",
  goodLabel: "会用了",
  queueLoading: "复习队列加载中...",
  queueEmpty: "当前没有到期待复习项，稍后再来巩固。",
  noTranslation: "暂无翻译",
  sourceSentence: "来源句子：",
  reviewStats: "复习次数",
  correct: "正确",
  incorrect: "错误",
  dash: "—",
  sessionHint: "正在复习你刚选中的表达。",
  manualSessionHint: "刚记下这个表达，现在试着自己用一下。",
  manualTrainingHintSubtle: "这是你刚收藏的表达，先别看参考句，试着说一句",
  fromExpressionLibrary: "来自表达库",
  fromExpressionMap: "来自表达地图",
  fromTodayTask: "来自今日任务",
  fromSelected: "来自你的选中表达",
  sourcePrefix: "来源",
  defaultHint: "正在进行当前到期表达复习。",
};
